### ISSUE TITLE
How to run pixie locally?

### ISSUE THREAD

**Issue by sfederici** [nathan/pixie#165]
Sorry for rising an issue but I didn't know how to ask otherwise. How do I run pixie locally? Do I need to install something? I tried to open index.html with all the major browsers but all I can see is the "see inside" blue button.

Thanks for any help

**Comment by IronManMark20** [comment]
If you want to run locally, you need to set up a server to serve the content of pixie. I use [Python](https://www.python.org/) to serve the content. Once you are in the directory of pixie, you can use `python -m SimpleHTTPServer` on the command line (for python 2.x) or for 3.x, you  can use `python3 -m http.server`

There are other ways to do it (such as using nodejs), but I prefer this way.

**Comment by sfederici** [comment]
I had tried to run it in xampp (where I usually run my local wordpress installation) but all I can see is still the "see inside" button. Would you mind giving me instructions on how to run it by installing nodejs? I'd rather have a way for my students to run it without them having to install a local server.

**Comment by IronManMark20** [comment]
I see. Did you make sure you cloned recursively? pixie has a "submodule" which you need to have. (Look in lib/visual). I am guessing you missed that? If so, you can update the submodule by running `git submodule update --init .`. If not, I would recommend [http-server](https://www.npmjs.com/package/http-server). If you have a node environment set up, you can really just ` npm install http-server -g` and then in the directory `node path/to/http-server`, then open 127.0.0.1:8080.

**Comment by IronManMark20** [comment]
@sfederici, did that help at all?

**Comment by nathan** [comment]
I run pixie locally with `http-server -s -p<whatever>` from the project directory.
